# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp_productor', models.CharField(max_length=100)),
                ('rfc_productor', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_n_productor', models.DateField()),
                ('persona_fisica_prod', models.BooleanField(default=True)),
                ('registro_padron', models.BooleanField()),
                ('id_suri', models.CharField(max_length=30)),
            ],
        ),
    ]
