# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0002_auto_20170627_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productor',
            old_name='nombre',
            new_name='nombre_productor',
        ),
    ]
