# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0003_auto_20170627_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productor',
            old_name='curp_productor',
            new_name='curp',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='fecha_n_productor',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='nombre_productor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='persona_fisica_prod',
            new_name='persona_fisica',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='rfc_productor',
            new_name='rfc',
        ),
    ]
