# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0004_auto_20170627_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ddr_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cader',
            },
        ),
        migrations.CreateModel(
            name='Ddr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ddr',
            },
        ),
        migrations.CreateModel(
            name='Ejido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ejido',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cader_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.BigIntegerField(unique=True)),
                ('folio_predio', models.CharField(max_length=100)),
                ('superficie_total', models.FloatField()),
                ('superficie_elegible', models.FloatField()),
                ('cader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Cader')),
                ('ddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Ddr')),
                ('ejido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Ejido')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Municipio')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Productor')),
            ],
        ),
    ]
