# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0006_auto_20170710_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predio',
            table='predios',
        ),
    ]
