# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0008_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('persona_fisica', models.BooleanField(default=True)),
                ('exede_limite_propiedad', models.BooleanField(default=False)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Ciclo')),
            ],
            options={
                'db_table': 'propietarios',
                'verbose_name': 'propietarios',
            },
        ),
        migrations.AlterField(
            model_name='predio',
            name='id_unico',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='propietario',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Predio'),
        ),
    ]
