# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0009_auto_20170823_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_generico', models.CharField(max_length=100)),
                ('variedad', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('rendimiento', models.FloatField(blank=True, null=True)),
                ('ciclo', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='predios.Predio')),
            ],
            options={
                'db_table': 'cultivos',
                'verbose_name': 'cultivos',
            },
        ),
    ]
