# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predios', '0010_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=100, null=True)),
                ('jefe_cader', models.BooleanField(db_column='JEFE CADER', default=False)),
                ('cader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Cader')),
                ('ddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Ddr')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
