# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predios.Cader'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ddr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predios.Ddr'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
